version: '3.1'

services:
  adonis_app:
    container_name: adonis_app
    restart: always
    depends_on:
      - postgres
    build:
      context: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules

  postgres:
    image: postgres:latest
    env_file: .env
    ports:
      - "5432:5432"
    secrets:
      - db_credentials
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: always
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    depends_on:
      - postgres
    env_file: .env
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin
    secrets:
      - db_credentials
    restart: always
    ports:
      - "5050:80"

secrets:
  db_credentials:
    file: .env
